import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import QueryProvider from "./components/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Scriptum Mens Lumen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {" "}
        <QueryProvider>
          <div className="min-h-screen bg-neutral-950">
            <main className="pt-16 lg:pt-0 min-h-screen">{children}</main>
          </div>
        </QueryProvider>
        <Script
          src="https://web-analytics-tan.vercel.app/api/track.js"
          data-site-id="sml"
          async
        ></Script>
      </body>
    </html>
  );
}
